VivumLab/VivumLab

.cz.toml, .pre-commit-config.yaml, Dockerfile, tasks/SanityCheckTasks.sh
=> build: added commitzen CLI for easy commiting

.cz.toml, Dockerfile, docker_helper.sh
=> fix(commitzen): fixes commitzen cli dependencies

docs/software/readarr.md, group_vars/all, mkdocs.yml, roles/readarr/tasks/main.yml, roles/readarr/templates/docker-compose.readarr.yml.j2, roles/vivumlab_config/templates/config.yml
=> feat(service): adding Readarr

git_sync_pre_commit
=> chore(cli): cli command for encryption changed

roles/nextcloud/templates/docker-compose.nextcloud.yml.j2
=> fix(service): Nextcloud (file permission set to user)

roles/nextcloud/tasks/main.yml, roles/nextcloud/templates/docker-compose.nextcloud.yml.j2
moving nextcloud to storage_dir to move data to the right location
=> fix: nextcloud move webroot to storage_dir

roles/vivumlab_config/templates/config.yml, roles/zammad/tasks/main.yml, roles/zammad/templates/docker-compose.zammad.yml.j2
version bumped to 3.4.0-17 & nginx_server_scheme https fix
=> fix(service): zammad version bump and nginx scheme fix

tasks/SanityCheckTasks.sh
Checks that the host docker daemon is turned on, and turns it on, if it isn't.
=> feat(core/tasks): Host docker daemon check

tasks/ConfigTasks.sh, tasks/LifecyleTasks.sh, tasks/TerraformTasks.sh, tasks/UpdateTasks.sh, tasks/helperFunctions.sh, tasks/vlabTasks.sh
adds the ability to debug the ansible playbook commands
super (-vvvv), to high (-vvv), to low/true (-vv) depending on desired verbosity
=> feat(core/tasks): Debug option for ansible playbook commands

roles/healthchecks/templates/docker-compose.healthchecks.yml.j2
=> fix(service): jinja2 trim_blocks

roles/authelia/tasks/main.yml, roles/authelia/templates/docker-compose.authelia.yml.j2
=> fix(service): authelia config bug

.travis.yml
=> refactor: changing travis to only run when merged to master

.travis.yml
=> fix(travis): addding pre-commit stage to travis

.travis.yml
=> fix(travis): travis pre-commit change to run-all

.travis.yml
=> fix(travis): change pip to pip3

.travis.yml
=> fix(travis): add python3

.travis.yml
=> fix(travis): apt needs sudo

.travis.yml
=> fix(travis): change language to python

.travis.yml
=> fix(travis): adding commitlint

roles/vivumlab_config/tasks/main.yml
=> style(lint): lint fixes

tasks/UserActionTasks.sh, tasks/helperFunctions.sh, tasks/vlabTasks.sh
adds some user tasks, tasks that allow the user in interact with the server in a way that they usually would, without leaving the vlab command line
=> feat(core): adds user tasks, that interact with the server

.travis.yml
=> fix: small fix / disable cleanup

.travis.yml
=> fix(travis): commitlint fix

.travis.yml
=> fix(travis): typo

.travis.yml
=> fix(travis): still trying to fix commitlint travis

.travis.yml
=> fix(travis): fixing commitlint

README.md
=> docs: add travis build information

.travis.yml
=> feat(release): update travis

.travis.yml
=> feat: add automatic changelog

.travis.yml
=> refactor(travis): branch set to master for release

.travis.yml
=> fix(travis): fix automatic changelog

.travis.yml
=> refactor(travis): git credentials

tasks/ConfigTasks.sh, tasks/LifecyleTasks.sh, tasks/SanityCheckTasks.sh, tasks/TerraformTasks.sh, tasks/UpdateTasks.sh, tasks/helperFunctions.sh, tasks/vlabTasks.sh
required extras for the ansible commands to use ssh keys
=> refactor(core): fixes commands using custom sshkeys

tasks/LifecyleTasks.sh
missing curly bracket in lifestyleTasks
=> refactor(core): fixed error in lifestyleTask file

roles/netdata/tasks/main.yml
=> fix(service): netdata necessities and nice-to-haves fix needs become yes

roles/vivumlab_setup/tasks/main.yml
debinstall.yml not named correctly in the main.yml file (deb_setup_docker.yml)
=> refactor(setup): fixed debinstall.yml not found error

.travis.yml
=> ci(travis): automation tasks (create changelog and bump version)

.travis.yml
=> chore: wrong variable

.travis.yml, commitlint.config.js, package-lock.json, package.json
=> ci(travis): add semantic-release

roles/vivumlab_config/templates/config.yml
=> fix: db version no main version change

package.json
=> fix(travis): automatic rebase back to dev

roles/netdata/tasks/main.yml, roles/netdata/templates/docker-compose.netdata.yml.j2
=> feat(service): :recycle: update netdata to keep config persistant

.cz.toml, .travis.yml, package.json
=> refactor(travis): :bookmark: disable automatic versioning for now

roles/netdata/tasks/main.yml
=> fix(service): adds CentOS support for Netdata

roles/bitwarden/templates/docker-compose.bitwarden.yml.j2
=> fix(service): :bug: fixed wrong ansible variable in bitwarden

package_template/docs/software/template.md
Refactor of the documentation template.
Fixes some discrepancies
=> refactor(documentation): fix minor issues with the docs template

tasks/UserActionTasks.sh
Fixed some universal stupid mistakes, made on my behalf.
SSH connections should work now
=> refactor(ssh): fixes ssh connection issues

CHANGELOG.md, Dockerfile, docs/dev/Developer-Tips.md, tasks/DeveloperTasks.sh, tasks/SanityCheckTasks.sh
Just needs the code changes, to make pre-commit less invasive for the user.
@denis-ev
=> feat(dev): allows choice to be a dev or a user

roles/vivumlab_deploy/tasks/main.yml, roles/vivumlab_wireguard/tasks/main.yml
Wireguard repos, updated.
Wireguard installs, updated
Added options for debian, and CentOS
=> refactor(service): wireguard repos updated

tasks/SanityCheckTasks.sh
This SSH stuff is really bugging me.
I'll get to the other stuff soon.
=> refactor(ssh): fix for sshkey check

tasks/helperFunctions.sh
Cleaning up helperFunctions.sh
Tested. ready for review
=> chore(core): cleanup helperFunctions.sh

.gitignore, mkdocs.yml, package_template/config.yml, package_template/mkdocs.yml, roles/vivumlab_config/templates/config.yml, tasks/AddPackageTasks.sh
change, and reconvene
Denis:
I added an experimental notice and that manual changes are required. 
With this merged we can add some more services and I can fix the small kinks in another PR.
=> fix(core): add new package wizard

tasks/helperFunctions.sh
I missed a few lines in the cleanup.
Sorry
=> chore(core): helpeFunctions.sh fix

tasks/helperFunctions.sh
Since we have been changing some code, a new unbound variable error has arisen.
This PR fixes the error
=> refactor(core): fixes unbound variable error (PASSWORDLESS_SSHKEY)

roles/vivumlab_deploy/tasks/main.yml
All the issues are slowly showing themselves.
=> refactor(deploy): copy log -> /etc/docker fix

.gitignore, playbook.ci_config.yml, roles/vivumlab_config/tasks/main.yml, tasks/ConfigTasks.sh, tasks/CoreTasks.sh, tasks/LifecyleTasks.sh, tasks/SanityCheckTasks.sh, tasks/ServiceTasks.sh, tasks/TerraformTasks.sh, tasks/UpdateTasks.sh, tasks/UserActionTasks.sh, yamllint.conf
This reverts commit cb5e88534285a47a04d2020383a4333ebf8b133d.
=> revert(core): allows user to create/use different config files (#133)

tasks/LifecyleTasks.sh, tasks/ServiceTasks.sh, tasks/UserActionTasks.sh
Making SSH command syntax more robust
=> refactor(core):Improving SSH command syntax

README.md
sets the 'readme' logo to the larger logo
=> chore(readme): update Logo

tasks/ConfigTasks.sh, tasks/helperFunctions.sh
I had a longer version of this fix, very early on in the whole VivumLab lifespan.
This fix, adds what is needed, but cuts down on code
=> refactor(config): unbound variable fix

roles/vivumlab_setup/tasks/debinstall.yml
fixes some issues with setuptools not been used/installed on debian
fixes issue with passlib not being installed
fixes issue with python-docker not being installed (htpasswd issue)
Thanks to Kitsu (for setuptools tip off).
Closes #127 
Closes #125
=> refactor(install): fixes some issues with setuptools

roles/vivumlab_deploy/tasks/main.yml, tasks/AddPackageTasks.sh, tasks/ConfigTasks.sh, tasks/CoreTasks.sh, tasks/DeveloperTasks.sh, tasks/LifecyleTasks.sh, tasks/SanityCheckTasks.sh, tasks/ServiceTasks.sh, tasks/TerraformTasks.sh, tasks/UpdateTasks.sh, tasks/UserActionTasks.sh
Just cleaning up some weird (but not breaking) code.
also adding some colour into the CLI output; gives it a more deliberate/polished feel
=> refactor(tasks): minor changes to the cli prompting

README.md
=> chore(readme): link fixes

roles/sui/tasks/main.yml, roles/sui/templates/config.json, roles/sui/templates/docker-compose.sui.yml.j2
It's possible that SUI may not be playing nicely with the latest version of traefik.
So that Vivum is usable for new users, I've added some temporary fixes..
We can work on this in the background
=> refactor(SUI): fix for SUI not working

docs/software/wificard.md, group_vars/all, mkdocs.yml, roles/vivumlab_config/templates/config.yml, roles/wificard/tasks/main.yml, roles/wificard/templates/docker-compose.wificard.yml.j2
=> feat(service): add wificard

roles/turtl/tasks/main.yml, roles/turtl/templates/docker-compose.turtl.yml.j2, roles/vivumlab_config/templates/config.yml
Fixes Turtl:
- no need to build the image, it pulls from docker hub
- appropriate folders are created
- looks for the correct db container
=> fix(service): fixes turtl

.github/workflows/02-lint-pr.yml, .github/workflows/04-release.yml, .github/workflows/05-docker-publish.yml
beautify the names and get semantic release dry run working
=> chore(ci): improve workflows

.github/workflows/07-trigger-release.yml
Trigger a release via manual run by syncing dev with master
=> chore(ci): trigger release via web

.github/workflows/04-docker-publish.yml
=> chore(ci): enable multi arch docker

.github/workflows/04-docker-publish.yml
forgot to add the repo before the tag
=> chore(ci): fix docker-publish workflow

.github/pr-status-label.json, .github/workflows/01-sanity-checks.yml
=> fix: fixes WIP failing status

.github/labeler.yml
=> chore(ci): automatically add labels to issues

tasks/service.rb
You know that issue you were having with service:list ... yeah I finally reproduced it. This fixes it.
=> fix: Fixes issue with modulo math that caused an error

tasks/utils.rb
=> fix: new config command

tasks/sanity_checks.rb
=> fix: removes ssh check

roles/codeserver/templates/docker-compose.codeserver.yml.j2
=> fix: code-server's password param is wrong.

tasks/config.rb, tasks/core.rb, tasks/lib/config_file_utils.rb, tasks/locales/en.yml, tasks/sanity_checks.rb, tasks/service.rb
=> fix: fixes 311

tasks/core.rb, tasks/service.rb, tasks/utils.rb
=> fix: skip tags setup

tasks/locales/en.yml, tasks/locales/fr.yml
@denis-ev I made the mistake to create my branch from master but it seems that I did not break anything by doing so, so luckily for this time, it can go through I suppose :).
Could you test it please? Unfortunately, I don't yet have a vivumlab setup to test this but I have been very careful. Although, I would not mind a linting to be sure. My current setup did not allow me to have pre-commit and all necessary tools because of the version of python3 that's too high... and I'm switching to a new machine in a week or 2 so I won't risk my python config in here.
=> chore: french localization

roles/plex/tasks/main.yml, roles/plex/templates/docker-compose.plex.yml.j2, roles/privatebin/tasks/main.yml, roles/privatebin/templates/docker-compose.privatebin.yml.j2
=> fix: update plex and privatebin tmpfs

roles/peertube/tasks/main.yml
Please, go through these steps before you submit a PR.
1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:
a. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-issue` or `feature/issue-templates`.
b. For Example `vlab update` doesn't throw any error. If it does, fix them first.
3. **After** these steps, you're ready to open a pull request.
a. Your pull request MUST NOT target the `master` branch on this repository. You want to target `dev` instead.
b. Give a descriptive title to your PR.
c. Provide a description of your changes.
d. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (always better if there is an …
=> fix: fixes issues 331 - whitespace issue in peertube

roles/restic/templates/docker-compose.restic.yml.j2, website/docs/core/Backup.md
=> fix: restic docker-compose.yml

docker/Dockerfile, docker/Dockerfile.dev, launch.sh
Should fix https://github.com/VivumLab/VivumLab/pull/345#issuecomment-773615766
In the `prod` stage of the Dockerfile, `ansible` is at `/opt/venv`. So the plugins should point at that too.
=> fix: dockerfile ansible plugins path

group_vars/all, roles/paperlessng/tasks/main.yml, roles/paperlessng/templates/docker-compose.paperlessng.yml.j2, roles/vivumlab_config/templates/config.yml, website/docs/software/paperless-ng.md, website/sidebars.js
Please, go through these steps before you submit a PR.
1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:
a. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-issue` or `feature/issue-templates`.
b. For Example `vlab update` doesn't throw any error. If it does, fix them first.
3. **After** these steps, you're ready to open a pull request.
a. Your pull request MUST NOT target the `master` branch on this repository. You want to target `dev` instead.
b. Give a descriptive title to your PR.
c. Provide a description of your changes.
d. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (always better if there is an …
=> feat: adds paperless-ng

docker/requirements.txt, roles/vivumlab_deploy/tasks/main.yml, tasks/service.rb, tasks/utils.rb
Please, go through these steps before you submit a PR.
1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:
a. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-issue` or `feature/issue-templates`.
b. For Example `vlab update` doesn't throw any error. If it does, fix them first.
3. **After** these steps, you're ready to open a pull request.
a. Your pull request MUST NOT target the `master` branch on this repository. You want to target `dev` instead.
b. Give a descriptive title to your PR.
c. Provide a description of your changes.
d. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (always better if there is an …
=> fix: vlab service SERVICENAME update

roles/nextcloud/tasks/main.yml, roles/nextcloud/templates/Dockerfile.j2, roles/nextcloud/templates/docker-compose.nextcloud.yml.j2, roles/vivumlab_config/templates/config.yml
Fixes the error I mentioned in https://github.com/VivumLab/VivumLab/pull/321#issue-560139202 and also improves the version handling for nextcloud.
=> fix: improve nextcloud permissions

group_vars/all, launch.sh, package_template/docs/software/template.md, roles/titra/tasks/main.yml, roles/titra/templates/docker-compose.titra.yml.j2, roles/vivumlab_config/templates/config.yml, website/docs/software/titra.md, website/sidebars.js
=> fix: add titra

docker/Dockerfile, docker/Dockerfile.dev, launch.sh, roles/vivumlab_deploy/tasks/main.yml, tasks/lib/config_file_utils.rb
Minor tweaks to account for new package versions, etc.
=> fix: misc-minor-fixes

docker/Dockerfile, docker/Dockerfile.dev
=> chore: docker publish

group_vars/all, roles/nocodb/tasks/main.yml, roles/nocodb/templates/docker-compose.nocodb.yml.j2, roles/vivumlab_config/templates/config.yml, website/docs/software/nocodb.md, website/sidebars.js
Adds NocoDB an Open Source AirTable alternative
=> feat: adds nocodb an air table alternative

.github/workflows/04-docker-publish.yml, docker/docker-bake.hcl
fixes: df7c0c1c63365e55eabd7b05e960d175d94c9537
=> fix: rename of ghaction-docker-meta to docker/metadata-action

roles/bookstack/templates/docker-compose.bookstack.yml.j2, roles/docs/templates/docker-compose.docs.yml.j2, roles/nextcloud/templates/docker-compose.nextcloud.yml.j2, roles/tick/templates/docker-compose.tick.yml.j2, roles/titra/templates/docker-compose.titra.yml.j2, roles/transmission/templates/docker-compose.transmission.yml.j2, roles/zammad/templates/docker-compose.zammad.yml.j2
to get rid of unnamed auto volumes
=> fix: adding tmpfs volumes

group_vars/all, roles/seafile/tasks/main.yml, roles/seafile/templates/docker-compose.seafile.yml.j2, roles/vivumlab_config/templates/config.yml, website/docs/software/seafile.md, website/sidebars.js
fixes #424
I tested the install on my machine, I am using it.
=> fix: adds seafile and seafile pro
