VivumLab/VivumLab

- tasks/ConfigTasks.sh
- tasks/LifecyleTasks.sh
- tasks/SanityCheckTasks.sh
- tasks/TerraformTasks.sh
- tasks/UpdateTasks.sh
- tasks/vlabTasks.sh
couple of things were added/fixed:
- added/ refactored error system... made more universal??..: essentially, now when a task initiates an ansible playbook command and it fails, there is no more multiline errors with insane line numbers. It just says 'error: <task>: <part of task (if applicable)>'
- added an exclaimation mark to the service params, this makes the service param a requirement (for the applicable playbook commands)
- made some user communication more concise.. terminal text can get pretty fast, VivumLab should get the point across quick
- got rid of some redundant code in the deploy task, that I forgot to remove earlier
- the stop and stop_one tasks had an errorneous description (said 'restart' instead of 'stop')
- put the exclamation mark inside the bash if conditional …
> refactor(core): refactor error system, fix service param, etc

- roles/vivumlab_deploy/tasks/main.yml
removes the red wall of "FAILED" text, at the end of the deploy play
> refactor(core): fixes deploy, removes red wall of text

- tasks/SanityCheckTasks.sh
- tasks/helperFunctions.sh
Wish I had caught this small issue before we cut 0.0.2.
Nevermind..
I remembered that in the sanity checks, the sshkey check didn't reflect the new sshkey name, so I've changed that too
> fixes small issue with sshkeys/bash

- roles/vivumlab_setup/tasks/centinstall.yml
Semanage may be required for some users, especially if they want to use a custom SSH port (which is good practise)
> refactor(core): installs utils package for semanage. CentOS

- tasks/UserActionTasks.sh
Separated crete and copy sshkey tasks.
Useful, when you are breaking down a server, and rebuilding it, again and again while testing (but you still want to use the old keys)
> refactor(ssh): separated create and copy sshkey functions

- tasks/SanityCheckTasks.sh
So I was getting this (not necessarily an error, but this..) erroneous message when running deploy
>Pre-commit is not installed
Contributions via git, require pre-commit. Run vlab dev_setup, to begin
after your deployment has finished, of course
So I toyed with it, and found the culprit.
However, the code can be placed, where I put the comment.. line 139
>     [ ! -f .git/pre-commit ] || pre-commit install && pre-commit install --install-hooks # > /dev/null 2>&1
and it will not display, this message..
>pre-commit installed at .git/hooks/pre-commit
I figured I would leave this choice to you.
if you want the message, remove the comment and everything after it,
if you don't want it, remove the '#'
Entirely up to you.
> refactor(precommit): fix for Vivum not recognising precommit install

- .gitignore
- playbook.ci_config.yml
- roles/vivumlab_config/tasks/main.yml
- tasks/ConfigTasks.sh
- tasks/CoreTasks.sh
- tasks/LifecyleTasks.sh
- tasks/SanityCheckTasks.sh
- tasks/TerraformTasks.sh
- tasks/UpdateTasks.sh
- tasks/UserActionTasks.sh
- yamllint.conf
allows user to create and to use different config files with the various vivumlab playbooks, using an extra user_config option.
vlab clone_config, sets a prefix, so the user can differentiate between the original and the user defined config files.
eg. answering vlab clone_config prompt, with... test1; will create test1-config.yml, test1-vault.yml, and test1-ansible_bash.vars.
Test and review, pleae
> feat(core): allows user to create/use different config files

- roles/vivumlab_wireguard/tasks/main.yml
When checking a debian distribution, wireguard ansible tasks were not able to discern the distribution version.
This PR fixes that
> refactor(wireguard): fixed minor syntax/typos in wireguard

- docs/dev/Developer-Tips.md
- roles/vivumlab_config/templates/config.yml
All of this repetitive commenting seems a bit counter-productive..
I've been thinking that the comments, are actually directed at the devs, so why not place this information into the documentation?
The documentation has been updated; the necessary information now exists in the developer document
If there are any issues with this, please bring it up sooner, rather than later
> refactor(config): remove unnecessary commenting

- roles/vivumlab_setup/tasks/main.yml
- roles/vivumlab_setup/tasks/ubuntuinstall.yml
Future proofing VivumLab, separates Debian and Ubuntu installers.
1. Easier to maintain, there are some minor differences in the script.
2. OS specific changes now, and in the future
3. Only need to be concerned with 'version' conditionals in script.
> refactor(install): Create ubuntu specific installer

- roles/vivumlab_setup/tasks/centinstall.yml
- roles/vivumlab_setup/tasks/debinstall.yml
FIX:
When pip installs docker-compose, it gets installed in /usr/local/bin, not /usr/bin, as per the service files.
It appears to happen on debian and on centos.
> refactor(setup): fix for docker-compose location issues

- roles/vivumlab_config/templates/config.yml
- roles/vivumlab_config/templates/vault.yml
- roles/vivumlab_deploy/templates/docker-compose.traefik.yml.j2
- roles/vivumlab_deploy/templates/traefik.yaml
For now, the typical use case.. deploying own the users own infrastructure, not using bastion, and not deploying mailu; the fix detailed below should work.
Fixes:
- Unless bastion is enabled, port 2222 is not exposed.
- Unless healthchecks OR bastion is enabled, port 25 in not exposed.
To consider, after merging (I would prefer these get sorted prior to merging, @denis-ev @codefriar):
- gitea ssh port should be changed from 2222 (will clash with bastion)
- vagrant 'ansible port' should be changed from 2222
- if healthchecks or bastion enable option is changed, after deploying; Vivum will need to restart traefik, after redeploying (still considering the best way to do this)
> refactor(traefik): not exposing open ports unless required

- .github/workflows/04-release.yml
- .github/workflows/06-mirror-back-to-dev.yml
Finally getting rid of the manual step when creating a release.
> chore(ci): mirror master to dev when release

- roles/vivumlab_setup/tasks/debinstall.yml
post wireguard fix (ansible python interpreter change)
debinstall needs to install passlib, virtualenv, etc with python3, not python
this is the fix
> fix(setup): use python3 with debinstall

- .github/workflows/03-release.yml
removes unnecessary step which builds and deploy multiple times to docker
> chore(ci): remove double build and deploy to docker

- roles/nextcloud/tasks/main.yml
- roles/vivumlab_deploy/tasks/main.yml
May partially fix https://github.com/VivumLab/VivumLab/issues/317
Nextcloud could not write into the `data/` directory because it was being created automatically by docker as it didn't exist.
This PR may contribute to fixing that by:
1. Ensure the Shared Mounts directories are always owned by the user, not by root (default for `/mnt`)
2. Ensure the Nextcloud role creates the necessary directories before launching the container.
The other commit present is more of a suggestion/question: I was also getting some permission errors when launching the container because it couldn't access the `entrypoint`. To fix that, I am skipping the build and using the image directly. However, what would be the correct fix? And why is the build necessary?
> fix: nextcloud

- roles/vivumlab_config/templates/config.yml
- roles/vivumlab_deploy/templates/traefik.yaml
We might want to test first without worrying to much about LE's limits,
so this would be an easier way of pointing to the staging servers:
https://acme-staging-v02.api.letsencrypt.org/directory
(See https://letsencrypt.org/docs/staging-environment/)
> feat: allow to set custom traefik env server

- roles/nextcloud/tasks/main.yml
- roles/nextcloud/templates/docker-compose.nextcloud.yml.j2
- roles/vivumlab_config/templates/config.yml
Allow to use MariaDB as an alternative to PostgreSQL
MariaDB/MySQL is the recommended DB engine by NC:
https://docs.nextcloud.com/server/20/admin_manual/configuration_database/linux_database_configuration.html#database-configuration
This allows you to choose between both (while keeping PG as the default)
It also provides a good template if you want to have both at the same time (for migrating between them, for example)
> feat: add another DB option to nextcloud

- docker/docker-entrypoint.sh
Fixes #316
Start the ssh agent and add all the added keys to it to avoid the error in the related issue.
Following the suggestions there solves the issue, so this adds those commands to the entrypoint to make it easier.
> fix: start ssh agent and add keys at start

- roles/vivumlab_config/templates/config.yml
Config is already set for the rootless image, this just sets the version to 1.14-rootless. 
To not jump versions right away.
> fix: change default gitea version

- roles/photoprism/tasks/main.yml
- roles/photoprism/templates/docker-compose.photoprism.yml.j2
1. Create folders correctly for `photoprism`. Similar to https://github.com/VivumLab/VivumLab/commit/618527f95a61593e28a1cf3a2a24516880b9ced0
2. Update docker compose configuration according to the docs:
Some additional security configuration is needed
We also need to use a specific image for ARM architectures
https://dl.photoprism.org/docker/docker-compose.yml
https://docs.photoprism.org/getting-started/docker-compose
https://docs.photoprism.org/getting-started/raspberry-pi
Tested on a Raspberry Pi 4
> fix: photoprism

- roles/nextcloud/tasks/main.yml
- roles/nextcloud/templates/docker-compose.nextcloud.yml.j2
- roles/vivumlab_config/templates/config.yml
We can choose to have the `apache` version instead of the `fpm-alpine` one
This also skips the local build, as it was causing problems for me in particular, when migrating from an existing server
As the local build with the changes is skipped, if this is chosen, the user needs to take care of setting up the proper folder permissions, which can be done with the option added next
---
This was causing issues for me when migrating from an existing instance.
It will potentially break compatibility if we wanted shared volumes between NC and other services, but the NC folder structure already makes it pretty complicated, so I think it won't  cause problems
Still, this is an option that is not enabled by default and should be used with caution, and is essential if we wanted the previous option of …
> feat: add other image options to nextcloud
